apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-aggregator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-aggregator
  template:
    metadata:
      labels:
        app: rss-aggregator
    spec:
      containers:
      - name: rss-aggregator
        image: your-dockerhub/rss-aggregator:latest
        ports:
        - containerPort: 80  # Correct format: list of objects (array of ports)
        env:
        - name: RSS_URL
          value: "https://bair.berkeley.edu/blog/feed.xml"
