apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rss-aggregator-hpa
spec:
  scaleTargetRef:
    apiVersoin: apps/v1
    kind: Deployment
    name: rss-aggregator
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type:Utilization
          averageUtilization: 50