apiVersion: v1
kind: PersistentVolume
metadata:
  name: rss-pv 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rss

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

