pipeline {
    agent any

    stages {
                stage('Install Minikube') {
            steps {
                script {
                    // Install dependencies
                    sh '''#!/bin/bash
                    set -e
                    curl -Lo minikube https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64
                    chmod +x minikube
                    sudo mv minikube /usr/local/bin/
                    '''
                }
            }
        }

        stage('Start Minikube') {
            steps {
                script {
                    // Delete existing cluster if it uses the wrong driver
                    sh 'minikube delete || true'  // Ignore errors if no cluster exists
                    
                    // Start Minikube using the 'docker' driver
                    sh '''#!/bin/bash
                    set -e
                    minikube start --driver=docker
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'docker build -t sriram9217/rss-aggregator:latest .'

                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'kubectl apply -f ci_cd/kubernetes/deployment.yaml'
                    sh 'kubectl apply -f ci_cd/kubernetes/service.yaml'
                    sh 'kubectl apply -f ci_cd/kubernetes/ingress.yaml'
                }
            }
        }
    }
}
