pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t sriram9217/rss-aggregator:latest .'

                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'kubectl apply -f ci_cd/kubernetes/deployment.yaml'
                    sh 'kubectl apply -f ci_cd/kubernetes/service.yaml'
                    sh 'kubectl apply -f ci_cd/kubernetes/ingress.yaml'
                }
            }
        }
    }
}
