pipeline {
    agent any

    environment {
        MINIKUBE_VERSION = "v1.33.1"  // set your preferred version
    }

    stages {
        stage('Install Minikube') {
            steps {
                script {
                    sh '''
                    curl -Lo minikube https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64
                    chmod +x minikube
                    sudo mv minikube /usr/local/bin/
                    '''
                }
            }
        }

        stage('Start Minikube') {
            steps {
                script {
                    sh 'minikube delete || true'
                    sh 'minikube start --driver=docker'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t sriram9217/rss-aggregator:latest .'
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                script {
                    sh 'kubectl apply -f ci_cd/kubernetes/deployment.yaml'
                    sh 'kubectl apply -f ci_cd/kubernetes/service.yaml'
                    sh 'kubectl apply -f ci_cd/kubernetes/ingress.yaml'
                }
            }
        }
    }
}
